<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class KelolaRuanganSeeder extends Seeder
{
    public function run()
    {
        DB::table('kelola_ruangan')->insert([
            [
                'nama_ruangan'     => 'Exhibition Area',
                'kapasitas'        => 100,
                'lokasi'           => 'Lantai 1',
                'fasilitas'        => 'Fasilitas Display Foto, Meja Display, Rak Display, Box Display, Pedestal',
                'jam_operasional'  => '09:00 - 18:00',
                'gambar'           => 'ruang_b.jpg',
                'lantai'           => 1,
                'status'           => 'Tersedia',
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'nama_ruangan'     => 'Amphiteater',
                'kapasitas'        => 100,
                'lokasi'           => 'Lantai 1',
                'fasilitas'        => 'Kursi, Meja, Stopkontak',
                'jam_operasional'  => '07:00 - 15:00',
                'gambar'           => 'img/ruangan/amphiteater.jpeg',
                'lantai'           => 1,
                'status'           => 'Tersedia',
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'nama_ruangan'     => 'Perpustakaan',
                'kapasitas'        => 30,
                'lokasi'           => 'Lantai 2',
                'fasilitas'        => 'Kursi, Meja Kerja, Meja Baca, Reading Corner, Stopkontak, Televisi LG, Proyektor',
                'jam_operasional'  => '08:00 - 20:00',
                'gambar'           => 'auditorium_d.jpg',
                'lantai'           => 2,
                'status'           => 'Tersedia',
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'nama_ruangan'     => 'Coworking Space',
                'kapasitas'        => 14,
                'lokasi'           => 'Lantai 2',
                'fasilitas'        => 'Kursi, Meja Kerja, Sofa White Board',
                'jam_operasional'  => '10:00 - 17:00',
                'gambar'           => 'workshop_e.jpg',
                'lantai'           => 2,
                'status'           => 'Tersedia',
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'nama_ruangan'     => 'Ruang kaca',
                'kapasitas'        => 30,
                'lokasi'           => 'Lantai 2',
                'fasilitas'        => 'Kursi, Meja Kerja, Stopkontak,Speaker Primatech, Microphone AKG (2), Screen Projector Microvision',
                'jam_operasional'  => '10:00 - 17:00',
                'gambar'           => 'workshop_e.jpg',
                'lantai'           => 2,
                'status'           => 'Tersedia',
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'nama_ruangan'     => 'Recording studio',
                'kapasitas'        => 8,
                'lokasi'           => 'Lantai 3',
                'fasilitas'        => 'Drum Akustik Sakae, Electric Guitar Fender Stratocaster, Guitar Acoustic Cort MR E NS, Electric Bass Fender Jazz, Bass Acoustic, Amplifier Marshall JCM900, Amplifier Behringer VT250X, Microphone Dynamic & Condenser, Preamp Neve 1073 DPA dan API 123, Audio Interface Apogee Symphony MKII, Speaker Monitor Recording Adam S1X, Pro DI Passive Direct Box Radial, Software Cubase, Pro Tools, Logic Pro X, Studio One',
                'jam_operasional'  => '10:00 - 17:00',
                'gambar'           => 'workshop_e.jpg',
                'lantai'           => 3,
                'status'           => 'Tersedia',
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'nama_ruangan'     => 'Auditorium',
                'kapasitas'        => 150,
                'lokasi'           => 'Lantai 3',
                'fasilitas'        => 'Kursi Bioskop (120), Kursi Portable (10), Meja Registrasi (1), Allen&Heath AR2412, Screen Projector, Infocus Epson, Microphone Wireless Audio Technica (4) - Speaker RCF (16) - Subwoofer RCF (2) - Onkyo AV Controller PR-SC5509 - Stand Mic (3) - Stand Partitur (1) - Televisi LG 43                ',
                'jam_operasional'  => '10:00 - 17:00',
                'gambar'           => 'workshop_e.jpg',
                'lantai'           => 3,
                'status'           => 'Tersedia',
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'nama_ruangan'     => 'Digital Content Studio',
                'kapasitas'        => 15,
                'lokasi'           => 'Lantai 4',
                'fasilitas'        => 'High Ceiling Roof 5x5m - Lemari Penyimpanan Bersandi - Standing Mirror - Light Stand Procore (3) - Light Boom Takara Alfa Spirit (2) - Video Light Avangarde AV-LED 100 (2) - Video Light Godox SL60W (2) - Portable RGB Light Stick (4) - Parabolic Softbox Godox QR-P70 (2) - Softbox Godox 80x120 (2) - Televisi Sony 40" (2) - Sony A7III - Nikon D7200 - Lensa Sony 28-70 - Lensa Nikon18-140mm - Lighting Profoto (2) - Trigger Profoto - LED Portable External (4) - ParLED (2) - Stand Giottos Air Cushion (8) - Stand Godox (4) - Background Paper Cream Background Kain Putih Background Kain Hitam (2) - Background Kain Cream - Background Kain Hijau (3) - Puluz Studio Box+Merah Biru Hijau BG - Background Triplek Kayu - Sterofoam Putih (3) - Clapper Board - Reflektor Gold & Silver - Speaker Eggel                ',
                'jam_operasional'  => '10:00 - 17:00',
                'gambar'           => 'workshop_e.jpg',
                'lantai'           => 3,
                'status'           => 'Tersedia',
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'nama_ruangan'     => 'Studio Tari',
                'kapasitas'        => 30,
                'lokasi'           => 'Lantai 3',
                'fasilitas'        => 'Speaker RCF (1) - Dinding Kaca - Lantai Vinyl',
                'jam_operasional'  => '10:00 - 17:00',
                'gambar'           => 'workshop_e.jpg',
                'lantai'           => 3,
                'status'           => 'Tersedia',
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'nama_ruangan'     => 'Teleconference Room',
                'kapasitas'        => 10,
                'lokasi'           => 'Lantai 4',
                'fasilitas'        => 'perangkat webcam, virtual hub',
                'jam_operasional'  => '10:00 - 17:00',
                'gambar'           => 'workshop_e.jpg',
                'lantai'           => 4,
                'status'           => 'Tersedia',
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'nama_ruangan'     => 'Studio Jahit',
                'kapasitas'        => 8,
                'lokasi'           => 'Lantai 4',
                'fasilitas'        => 'Mesin Jahit JUKI HZL-27z (5) - Mesin Obras JUKI MO-50e (2) - Mesin Bordir Surya S- 1201PT (1) - Kursi (7)',
                'jam_operasional'  => '10:00 - 17:00',
                'gambar'           => 'workshop_e.jpg',
                'lantai'           => 4,
                'status'           => 'Tersedia',
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'nama_ruangan'     => 'Studio Animasi & Editing',
                'kapasitas'        => 10,
                'lokasi'           => 'Lantai 4',
                'fasilitas'        => ' CPU HP Z440 (2) - CPU HP Z640 (6) - CPU Axioo (4) - Monitor HP Z27n (3) - Monitor HP N240 (5) - Monitor Axioo (4) - Headset Logitech (5) - Wacom Intuos Art (4) Software Design/Editing: Adobe Family, Figma, Davinci Resolve, Sony Vegas - Software Animasi/3D/Rendering: Blender, Cinema 4D, Unreal Engine 5, Houdini, Marvelous Designer, Toon Boom Harmony, Zbrush',
                'jam_operasional'  => '10:00 - 17:00',
                'gambar'           => 'workshop_e.jpg',
                'lantai'           => 4,
                'status'           => 'Tersedia',
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'nama_ruangan'     => 'Studio Fashion',
                'kapasitas'        => 30,
                'lokasi'           => 'Lantai 5',
                'fasilitas'        => 'Kursi - Meja Panjang (1) - Microphone Speaker RCF (1) - Mixer Primatech',
                'jam_operasional'  => '10:00 - 17:00',
                'gambar'           => 'workshop_e.jpg',
                'lantai'           => 5,
                'status'           => 'Tersedia',
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
            [
                'nama_ruangan'     => 'Aula',
                'kapasitas'        => 80,
                'lokasi'           => 'Lantai 5',
                'fasilitas'        => 'Kursi Kampus (60) - Kursi Portable (4) - Meja Panjang (1) - Meja Registrasi (2) - Meja Narasumber (1) - Speaker Primatech (1) - Screen Projector Microvision - Microphone AKG (2) - Stopkontak',
                'jam_operasional'  => '10:00 - 17:00',
                'gambar'           => 'workshop_e.jpg',
                'lantai'           => 5,
                'status'           => 'Tersedia',
                'created_at'       => Carbon::now(),
                'updated_at'       => Carbon::now(),
            ],
        ]);
    }
}
