<?php

namespace Database\Seeders;

use App\Models\PeminjamanRuangan;
use Illuminate\Database\Seeder;

class PeminjamanRuanganSeeder extends Seeder
{
    public function run()
    {
        $peminjaman = [
            [
                'user_id' => 1,
                'ruangan_id' => 1,
                'nama_peminjam' => 'John Doe',
                'email_peminjam' => 'john@example.com',
                'telepon_peminjam' => '081234567890',
                'instansi_peminjam' => 'PT Example',
                'kegiatan' => 'Tech Meeting 2024',
                'deskripsi_kegiatan' => 'Diskusi proyek dengan tim IT',
                'tanggal_peminjaman' => '2025-05-15',
                'waktu_mulai' => '09:00:00',
                'waktu_selesai' => '12:00:00',
                'jumlah_peserta' => 20,
                'status' => 'pending',
                'surat_peminjaman' => 'surat_peminjaman_1.pdf',
                'rejection_reason' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'user_id' => 2,
                'ruangan_id' => 2,
                'nama_peminjam' => 'Jane Smith',
                'email_peminjam' => 'jane@example.com',
                'telepon_peminjam' => '081234567891',
                'instansi_peminjam' => 'PT Sample',
                'kegiatan' => 'Design Workshop 2024',
                'deskripsi_kegiatan' => 'Workshop desain UI/UX untuk tim desain',
                'tanggal_peminjaman' => '2025-05-16',
                'waktu_mulai' => '13:00:00',
                'waktu_selesai' => '16:00:00',
                'jumlah_peserta' => 15,
                'status' => 'pending',
                'surat_peminjaman' => 'surat_peminjaman_2.pdf',
                'rejection_reason' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'user_id' => 3,
                'ruangan_id' => 3,
                'nama_peminjam' => 'Andi Pratama',
                'email_peminjam' => 'andi@example.com',
                'telepon_peminjam' => '081234567892',
                'instansi_peminjam' => 'Universitas A',
                'kegiatan' => 'Seminar AI',
                'deskripsi_kegiatan' => 'Seminar pengenalan AI',
                'tanggal_peminjaman' => '2025-01-10',
                'waktu_mulai' => '10:00:00',
                'waktu_selesai' => '13:00:00',
                'jumlah_peserta' => 50,
                'status' => 'pending',
                'surat_peminjaman' => 'surat_peminjaman_3.pdf',
                'rejection_reason' => null,
                'created_at' => '2024-01-05 08:00:00',
                'updated_at' => '2024-01-05 08:00:00'
            ],
            [
                'user_id' => 4,
                'ruangan_id' => 4,
                'nama_peminjam' => 'Budi Santoso',
                'email_peminjam' => 'budi@example.com',
                'telepon_peminjam' => '081234567893',
                'instansi_peminjam' => 'PT Teknologi',
                'kegiatan' => 'Training Karyawan',
                'deskripsi_kegiatan' => 'Pelatihan software internal',
                'tanggal_peminjaman' => '2025-01-20',
                'waktu_mulai' => '09:00:00',
                'waktu_selesai' => '11:00:00',
                'jumlah_peserta' => 25,
                'status' => 'pending',
                'surat_peminjaman' => 'surat_peminjaman_4.pdf',
                'rejection_reason' => null,
                'created_at' => '2025-01-12 09:00:00',
                'updated_at' => '2025-01-12 09:00:00'
            ],
            [
                'user_id' => 5,
                'ruangan_id' => 5,
                'nama_peminjam' => 'Citra Lestari',
                'email_peminjam' => 'citra@example.com',
                'telepon_peminjam' => '081234567894',
                'instansi_peminjam' => 'Lembaga X',
                'kegiatan' => 'Rapat Koordinasi',
                'deskripsi_kegiatan' => 'Koordinasi antar divisi',
                'tanggal_peminjaman' => '2025-02-08',
                'waktu_mulai' => '14:00:00',
                'waktu_selesai' => '17:00:00',
                'jumlah_peserta' => 30,
                'status' => 'pending',
                'surat_peminjaman' => 'surat_peminjaman_5.pdf',
                'rejection_reason' => null,
                'created_at' => '2025-02-02 10:00:00',
                'updated_at' => '2025-02-02 10:00:00'
            ],
            [
                'user_id' => 6,
                'ruangan_id' => 1,
                'nama_peminjam' => 'Dedi Kurniawan',
                'email_peminjam' => 'dedi@example.com',
                'telepon_peminjam' => '081234567895',
                'instansi_peminjam' => 'Startup Hub',
                'kegiatan' => 'Pitching Day',
                'deskripsi_kegiatan' => 'Presentasi ide bisnis',
                'tanggal_peminjaman' => '2025-02-20',
                'waktu_mulai' => '11:00:00',
                'waktu_selesai' => '13:30:00',
                'jumlah_peserta' => 10,
                'status' => 'pending',
                'surat_peminjaman' => 'surat_peminjaman_6.pdf',
                'rejection_reason' => null,
                'created_at' => '2025-02-10 11:00:00',
                'updated_at' => '2025-02-10 11:00:00'
            ],
            [
                'user_id' => 1,
                'ruangan_id' => 1,
                'nama_peminjam' => 'Eka Sari',
                'email_peminjam' => 'eka@example.com',
                'telepon_peminjam' => '081234567896',
                'instansi_peminjam' => 'Komunitas UX',
                'kegiatan' => 'UX Meetup',
                'deskripsi_kegiatan' => 'Diskusi komunitas UX lokal',
                'tanggal_peminjaman' => '2025-03-10',
                'waktu_mulai' => '18:00:00',
                'waktu_selesai' => '20:00:00',
                'jumlah_peserta' => 40,
                'status' => 'pending',
                'surat_peminjaman' => 'surat_peminjaman_7.pdf',
                'rejection_reason' => null,
                'created_at' => '2025-03-01 08:30:00',
                'updated_at' => '2025-03-01 08:30:00'
            ],
            [
                'user_id' => 2,
                'ruangan_id' => 1,
                'nama_peminjam' => 'Fajar Nugroho',
                'email_peminjam' => 'fajar@example.com',
                'telepon_peminjam' => '081234567897',
                'instansi_peminjam' => 'Developer ID',
                'kegiatan' => 'Hackathon',
                'deskripsi_kegiatan' => 'Lomba coding 24 jam',
                'tanggal_peminjaman' => '2025-03-21',
                'waktu_mulai' => '08:00:00',
                'waktu_selesai' => '08:00:00',
                'jumlah_peserta' => 60,
                'status' => 'pending',
                'surat_peminjaman' => 'surat_peminjaman_8.pdf',
                'rejection_reason' => null,
                'created_at' => '2025-03-05 09:00:00',
                'updated_at' => '2025-03-05 09:00:00'
            ],
            [
                'user_id' => 3,
                'ruangan_id' => 2,
                'nama_peminjam' => 'Gita Ayu',
                'email_peminjam' => 'gita@example.com',
                'telepon_peminjam' => '081234567898',
                'instansi_peminjam' => 'NGO Peduli',
                'kegiatan' => 'Diskusi Sosial',
                'deskripsi_kegiatan' => 'Diskusi isu sosial dan kampanye',
                'tanggal_peminjaman' => '2024-04-05',
                'waktu_mulai' => '13:00:00',
                'waktu_selesai' => '15:00:00',
                'jumlah_peserta' => 35,
                'status' => 'pending',
                'surat_peminjaman' => 'surat_peminjaman_9.pdf',
                'rejection_reason' => null,
                'created_at' => '2024-04-01 09:00:00',
                'updated_at' => '2024-04-01 09:00:00'
            ],
            [
                'user_id' => 4,
                'ruangan_id' => 5,
                'nama_peminjam' => 'Hendra Saputra',
                'email_peminjam' => 'hendra@example.com',
                'telepon_peminjam' => '081234567899',
                'instansi_peminjam' => 'Creative Minds',
                'kegiatan' => 'Workshop Kreatif',
                'deskripsi_kegiatan' => 'Pelatihan desain grafis',
                'tanggal_peminjaman' => '2024-04-19',
                'waktu_mulai' => '10:00:00',
                'waktu_selesai' => '12:30:00',
                'jumlah_peserta' => 28,
                'status' => 'pending',
                'surat_peminjaman' => 'surat_peminjaman_10.pdf',
                'rejection_reason' => null,
                'created_at' => '2024-04-10 10:00:00',
                'updated_at' => '2024-04-10 10:00:00'
            ],
            [
                'user_id' => 5,
                'ruangan_id' => 1,
                'nama_peminjam' => 'Indra Wahyudi',
                'email_peminjam' => 'indra@example.com',
                'telepon_peminjam' => '081234568000',
                'instansi_peminjam' => 'PT Energi',
                'kegiatan' => 'Rapat Tahunan',
                'deskripsi_kegiatan' => 'Laporan tahunan dan evaluasi',
                'tanggal_peminjaman' => '2024-05-10',
                'waktu_mulai' => '09:00:00',
                'waktu_selesai' => '12:00:00',
                'jumlah_peserta' => 45,
                'status' => 'pending',
                'surat_peminjaman' => 'surat_peminjaman_11.pdf',
                'rejection_reason' => null,
                'created_at' => '2024-05-01 08:00:00',
                'updated_at' => '2024-05-01 08:00:00'
            ],
            [
                'user_id' => 6,
                'ruangan_id' => 3,
                'nama_peminjam' => 'Joko Prabowo',
                'email_peminjam' => 'joko@example.com',
                'telepon_peminjam' => '081234568001',
                'instansi_peminjam' => 'PT Transportasi',
                'kegiatan' => 'Sosialisasi Proyek',
                'deskripsi_kegiatan' => 'Sosialisasi proyek kereta cepat',
                'tanggal_peminjaman' => '2024-05-25',
                'waktu_mulai' => '13:00:00',
                'waktu_selesai' => '15:00:00',
                'jumlah_peserta' => 38,
                'status' => 'pending',
                'surat_peminjaman' => 'surat_peminjaman_12.pdf',
                'rejection_reason' => null,
                'created_at' => '2024-05-10 10:00:00',
                'updated_at' => '2024-05-10 10:00:00'
            ],
            [
                'user_id' => 1,
                'ruangan_id' => 3,
                'nama_peminjam' => 'Kiki Amelia',
                'email_peminjam' => 'kiki@example.com',
                'telepon_peminjam' => '081234568002',
                'instansi_peminjam' => 'Startup Edu',
                'kegiatan' => 'Pelatihan Online',
                'deskripsi_kegiatan' => 'Pelatihan e-learning untuk guru',
                'tanggal_peminjaman' => '2024-06-03',
                'waktu_mulai' => '09:00:00',
                'waktu_selesai' => '11:30:00',
                'jumlah_peserta' => 30,
                'status' => 'pending',
                'surat_peminjaman' => 'surat_peminjaman_13.pdf',
                'rejection_reason' => null,
                'created_at' => '2024-06-01 09:30:00',
                'updated_at' => '2024-06-01 09:30:00'
            ],
            [
                'user_id' => 2,
                'ruangan_id' => 4,
                'nama_peminjam' => 'Lia Paramita',
                'email_peminjam' => 'lia@example.com',
                'telepon_peminjam' => '081234568003',
                'instansi_peminjam' => 'Biro Hukum',
                'kegiatan' => 'Diskusi RUU',
                'deskripsi_kegiatan' => 'Pembahasan revisi undang-undang',
                'tanggal_peminjaman' => '2024-06-18',
                'waktu_mulai' => '10:00:00',
                'waktu_selesai' => '12:00:00',
                'jumlah_peserta' => 22,
                'status' => 'pending',
                'surat_peminjaman' => 'surat_peminjaman_14.pdf',
                'rejection_reason' => null,
                'created_at' => '2024-06-05 10:00:00',
                'updated_at' => '2024-06-05 10:00:00'
            ],
            [
                'user_id' => 3,
                'ruangan_id' => 3,
                'nama_peminjam' => 'Miko Ramadhan',
                'email_peminjam' => 'miko@example.com',
                'telepon_peminjam' => '081234568004',
                'instansi_peminjam' => 'Komunitas Data',
                'kegiatan' => 'Pelatihan Data Analyst',
                'deskripsi_kegiatan' => 'Belajar analisis data dasar',
                'tanggal_peminjaman' => '2024-07-09',
                'waktu_mulai' => '14:00:00',
                'waktu_selesai' => '16:00:00',
                'jumlah_peserta' => 20,
                'status' => 'pending',
                'surat_peminjaman' => 'surat_peminjaman_15.pdf',
                'rejection_reason' => null,
                'created_at' => '2024-07-01 10:00:00',
                'updated_at' => '2024-07-01 10:00:00'
            ],
            [
                'user_id' => 4,
                'ruangan_id' => 1,
                'nama_peminjam' => 'Nina Larasati',
                'email_peminjam' => 'nina@example.com',
                'telepon_peminjam' => '081234568005',
                'instansi_peminjam' => 'Yayasan Harapan',
                'kegiatan' => 'Sosialisasi Kesehatan',
                'deskripsi_kegiatan' => 'Edukasi gizi untuk keluarga',
                'tanggal_peminjaman' => '2024-08-10',
                'waktu_mulai' => '09:00:00',
                'waktu_selesai' => '11:00:00',
                'jumlah_peserta' => 50,
                'status' => 'pending',
                'surat_peminjaman' => 'surat_peminjaman_16.pdf',
                'rejection_reason' => null,
                'created_at' => '2024-08-01 09:00:00',
                'updated_at' => '2024-08-01 09:00:00'
            ],
            [
                'user_id' => 1,
                'ruangan_id' => 1,
                'nama_peminjam' => 'Oki Setiawan',
                'email_peminjam' => 'oki@example.com',
                'telepon_peminjam' => '081234568006',
                'instansi_peminjam' => 'Koperasi Digital',
                'kegiatan' => 'Rapat Pengurus',
                'deskripsi_kegiatan' => 'Evaluasi dan rencana kerja tahunan',
                'tanggal_peminjaman' => '2024-09-15',
                'waktu_mulai' => '13:00:00',
                'waktu_selesai' => '15:30:00',
                'jumlah_peserta' => 18,
                'status' => 'pending',
                'surat_peminjaman' => 'surat_peminjaman_17.pdf',
                'rejection_reason' => null,
                'created_at' => '2024-09-01 10:00:00',
                'updated_at' => '2024-09-01 10:00:00'
            ],
            [
                'user_id' => 2,
                'ruangan_id' => 2,
                'nama_peminjam' => 'Putri Maharani',
                'email_peminjam' => 'putri@example.com',
                'telepon_peminjam' => '081234568007',
                'instansi_peminjam' => 'Event Organizer A',
                'kegiatan' => 'Briefing Crew',
                'deskripsi_kegiatan' => 'Koordinasi teknis acara',
                'tanggal_peminjaman' => '2024-09-28',
                'waktu_mulai' => '15:00:00',
                'waktu_selesai' => '17:00:00',
                'jumlah_peserta' => 12,
                'status' => 'pending',
                'surat_peminjaman' => 'surat_peminjaman_18.pdf',
                'rejection_reason' => null,
                'created_at' => '2024-09-10 11:00:00',
                'updated_at' => '2024-09-10 11:00:00'
            ],
            [
                'user_id' => 3,
                'ruangan_id' => 4,
                'nama_peminjam' => 'Raka Ardiansyah',
                'email_peminjam' => 'raka@example.com',
                'telepon_peminjam' => '081234568008',
                'instansi_peminjam' => 'PT Solusi',
                'kegiatan' => 'Workshop Manajemen',
                'deskripsi_kegiatan' => 'Pelatihan soft skill manajerial',
                'tanggal_peminjaman' => '2024-10-12',
                'waktu_mulai' => '09:00:00',
                'waktu_selesai' => '12:00:00',
                'jumlah_peserta' => 40,
                'status' => 'pending',
                'surat_peminjaman' => 'surat_peminjaman_19.pdf',
                'rejection_reason' => null,
                'created_at' => '2024-10-01 08:00:00',
                'updated_at' => '2024-10-01 08:00:00'
            ],
            [
                'user_id' => 4,
                'ruangan_id' => 5,
                'nama_peminjam' => 'Santi Dewi',
                'email_peminjam' => 'santi@example.com',
                'telepon_peminjam' => '081234568009',
                'instansi_peminjam' => 'Forum Perempuan',
                'kegiatan' => 'Pelatihan Kepemimpinan',
                'deskripsi_kegiatan' => 'Empowerment untuk pemimpin perempuan',
                'tanggal_peminjaman' => '2024-12-08',
                'waktu_mulai' => '10:00:00',
                'waktu_selesai' => '12:00:00',
                'jumlah_peserta' => 35,
                'status' => 'pending',
                'surat_peminjaman' => 'surat_peminjaman_20.pdf',
                'rejection_reason' => null,
                'created_at' => '2024-12-01 08:30:00',
                'updated_at' => '2024-12-01 08:30:00'
            ]
        ];

        foreach ($peminjaman as $data) {
            PeminjamanRuangan::create($data);
        }
    }
}
